services:
  staging:
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=staging
      - OHM_USERNAME=${OHM_USERNAME}
      - OHM_PASSWORD=${OHM_PASSWORD}
    depends_on:
      chrome:
        condition: service_healthy
    command: ["python", "main.py"]

  production:
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=production
      - OHM_USERNAME=${OHM_USERNAME}
      - OHM_PASSWORD=${OHM_PASSWORD}
    depends_on:
      chrome:
        condition: service_healthy
    command: ["python", "main.py"]

  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: "2gb"
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_SESSION_TIMEOUT=120
      - SE_VNC_NO_PASSWORD=1
    healthcheck:
      test: ["CMD-SHELL", "(curl -fsS http://localhost:4444/status || curl -fsS http://localhost:4444/wd/hub/status) | grep -E '\"ready\"\\s*:\\s*true' >/dev/null 2>&1"]
      interval: 5s
      timeout: 3s
      retries: 60
      start_period: 25s
    volumes:
      - /dev/shm:/dev/shm